enum ReleaseStatus {
  PLANNED
  ONGOING
  DONE
}

type Release {
  id: ID!
  name: String!
  date: String!
  additionalInfo: String
  completedSteps: [Int!]!
  status: ReleaseStatus!
  userId: String!
}

input CreateReleaseInput {
  name: String!
  date: String!
  additionalInfo: String
  userId: String!
}

type Query {
  releases(userId: String!): [Release!]!
  release(id: ID!): Release
}

type Mutation {
  createRelease(input: CreateReleaseInput!): Release!
  updateChecklist(id: ID!, completedSteps: [Int!]!): Release!
  updateAdditionalInfo(id: ID!, additionalInfo: String): Release!
  deleteRelease(id: ID!): Boolean!
}